version: '3.8'

services:
  drone_navigation_system:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: robothon26_drone_container
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Note: Webots often requires NVIDIA runtime for 3D simulation inside docker if visual rendering is needed.
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./docs:/drone_ws/docs:rw
    command: /bin/bash -c "source /drone_ws/install/setup.bash && ros2 launch src/launch/master_launch.py"
